version: '3.3'

services: 
      web:
        container_name: app
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        image: nish9900/demo
        ports: 
          - "9000:3000"
        depends_on:
          - database
        networks:
          - frontend
          - backend
        
        
      database:
        container_name: mongo
        image: mongo
        environment:
          - MONGO_URI=mongodb://mongo:27017/demo
        ports: 
          - "27017:27017"
        volumes:
          - ./db:/data/db
        networks:
          - backend
        

networks:
  frontend:
  backend:
    


